theme: minima
title: My Protoype Blog
author: Hal Rodriguez
email: halr@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Hal's protoype blog

# social links
twitter_username: halr66 # DO NOT include the @ character, or else the build will fail!
github_username:  halr # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
